"""Sample construction data for the TACO demo.

A realistic mechanical HVAC BOM for "Oakridge Medical Center" — a
12-line-item bill of materials that validates against spec/schemas/bom-v1.json.
"""

SAMPLE_BOM: dict = {
    "projectId": "PRJ-2026-OAKRIDGE-MEDICAL",
    "revision": "Rev C",
    "trade": "mechanical",
    "csiDivision": "23",
    "lineItems": [
        {
            "id": "LI-001",
            "description": "Rooftop Unit, 25-ton, gas/electric, VAV",
            "quantity": 2,
            "unit": "EA",
            "size": "25 ton",
            "material": "steel",
            "specSection": "23 74 13",
            "sourceSheet": "M-101",
            "location": "Roof Level",
            "alternates": [
                {
                    "description": "Carrier 48HC",
                    "manufacturer": "Carrier",
                    "partNumber": "48HC-A28",
                },
                {
                    "description": "Trane Voyager",
                    "manufacturer": "Trane",
                    "partNumber": "TCD-300",
                },
            ],
        },
        {
            "id": "LI-002",
            "description": "Air Handling Unit, 10,000 CFM, with economizer",
            "quantity": 3,
            "unit": "EA",
            "size": "10000 CFM",
            "material": "galvanized steel",
            "specSection": "23 73 13",
            "sourceSheet": "M-102",
            "location": "Mechanical Room Level 1",
        },
        {
            "id": "LI-003",
            "description": "Rectangular duct, galvanized, 24x12 inches",
            "quantity": 480,
            "unit": "LF",
            "size": "24x12 inch",
            "material": "galvanized steel",
            "specSection": "23 31 13",
            "sourceSheet": "M-201",
            "location": "Level 2 Wing B",
        },
        {
            "id": "LI-004",
            "description": "Round spiral duct, galvanized, 14-inch diameter",
            "quantity": 320,
            "unit": "LF",
            "size": "14 inch",
            "material": "galvanized steel",
            "specSection": "23 31 13",
            "sourceSheet": "M-201",
            "location": "Level 2 Wing A",
        },
        {
            "id": "LI-005",
            "description": "VAV terminal unit with hot water reheat coil",
            "quantity": 24,
            "unit": "EA",
            "size": "12 inch inlet",
            "material": "galvanized steel",
            "specSection": "23 36 13",
            "sourceSheet": "M-301",
            "location": "Levels 1-3",
        },
        {
            "id": "LI-006",
            "description": "Chilled water pipe, copper Type L",
            "quantity": 650,
            "unit": "LF",
            "size": "4 inch",
            "material": "copper",
            "specSection": "23 21 13",
            "sourceSheet": "M-401",
            "location": "Mechanical room to Level 3",
        },
        {
            "id": "LI-007",
            "description": "Hot water pipe, copper Type L",
            "quantity": 450,
            "unit": "LF",
            "size": "2 inch",
            "material": "copper",
            "specSection": "23 21 13",
            "sourceSheet": "M-401",
            "location": "Boiler room distribution",
        },
        {
            "id": "LI-008",
            "description": "Pipe insulation, fiberglass with ASJ jacket",
            "quantity": 1100,
            "unit": "LF",
            "size": "1.5 inch wall",
            "material": "fiberglass",
            "specSection": "23 07 13",
            "sourceSheet": "M-401",
            "location": "All piping runs",
        },
        {
            "id": "LI-009",
            "description": "Condensing gas boiler, 2000 MBH",
            "quantity": 2,
            "unit": "EA",
            "size": "2000 MBH",
            "material": "stainless steel",
            "specSection": "23 52 13",
            "sourceSheet": "M-102",
            "location": "Boiler Room Level B1",
        },
        {
            "id": "LI-010",
            "description": "Base-mounted centrifugal pump, 40 GPM",
            "quantity": 4,
            "unit": "EA",
            "size": "40 GPM",
            "material": "cast iron",
            "specSection": "23 21 23",
            "sourceSheet": "M-102",
            "location": "Mechanical Room Level 1",
        },
        {
            "id": "LI-011",
            "description": "DDC controller, BACnet MS/TP, 16-point",
            "quantity": 12,
            "unit": "EA",
            "size": "16-point",
            "material": "electronic",
            "specSection": "23 09 23",
            "sourceSheet": "M-501",
            "location": "Distributed across Levels 1-3",
        },
        {
            "id": "LI-012",
            "description": "Exhaust fan, centrifugal inline, 2000 CFM",
            "quantity": 6,
            "unit": "EA",
            "size": "2000 CFM",
            "material": "aluminum",
            "specSection": "23 34 13",
            "sourceSheet": "M-103",
            "location": "Roof Level",
        },
    ],
    "metadata": {
        "generatedBy": "manual-entry",
        "generatedAt": "2026-02-28T10:30:00Z",
        "confidence": 0.95,
        "sourceDocuments": [
            {
                "filename": "Oakridge Medical Center - Mechanical.pdf",
                "sheetId": "M-101",
                "revision": "C",
            },
            {
                "filename": "Oakridge Medical Center - Mechanical.pdf",
                "sheetId": "M-201",
                "revision": "C",
            },
            {
                "filename": "Oakridge Medical Center - Mechanical.pdf",
                "sheetId": "M-301",
                "revision": "C",
            },
            {
                "filename": "Oakridge Medical Center - Mechanical.pdf",
                "sheetId": "M-401",
                "revision": "C",
            },
        ],
        "flaggedItems": [
            {
                "lineItemId": "LI-006",
                "reason": "Verify 4-inch pipe size — schedule shows 3-inch on some runs",
                "severity": "warning",
            },
            {
                "lineItemId": "LI-005",
                "reason": "VAV box sizing not confirmed against latest load calcs",
                "severity": "info",
            },
        ],
    },
}
